// generated by newgenasym  Tue Mar 22 15:44:36 2016


module res_smd (\1 , \2 , \3 , tab);
    inout \1 ;
    inout \2 ;
    inout \3 ;
    input tab;


    initial
        begin
        end

endmodule
