-- generated by newgenasym Wed Feb 24 23:31:58 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cap_np is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end cap_np;
