// generated by newgenasym  Tue Dec 15 12:47:20 2015


module max30102 (\/int , gnd, ir_drv, nc_1, nc_2, nc_3, nc_4, pgnd, r_drv, scl,
        sda, vdd, \vled+_1 , \vled+_2 );
    input \/int ;
    input gnd;
    inout ir_drv;
    inout nc_1;
    inout nc_2;
    inout nc_3;
    inout nc_4;
    input pgnd;
    inout r_drv;
    input scl;
    inout sda;
    input vdd;
    input \vled+_1 ;
    input \vled+_2 ;


    initial
        begin
        end

endmodule
