// generated by newgenasym  Tue Apr 12 16:16:22 2016


module induct (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
