// generated by newgenasym  Mon Mar 24 11:33:12 2014


module max14595 (\/ts , gnd, iovcc1, iovcc2, iovl1, iovl2, vcc, vl);
    input \/ts ;
    input gnd;
    inout iovcc1;
    inout iovcc2;
    inout iovl1;
    inout iovl2;
    input vcc;
    input vl;


    initial
        begin
        end

endmodule
