-- generated by newgenasym Mon Mar 24 11:33:12 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max14595 is
    port (    
	\/ts\:     IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	IOVCC1:    INOUT  STD_LOGIC;    
	IOVCC2:    INOUT  STD_LOGIC;    
	IOVL1:     INOUT  STD_LOGIC;    
	IOVL2:     INOUT  STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	VL:        IN     STD_LOGIC);
end max14595;
