-- generated by newgenasym Tue Apr 12 16:16:22 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity induct is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end induct;
