// generated by newgenasym  Mon Dec 14 23:12:55 2015


module max1921 (\/shdn , agnd, in, lx, out, pgnd);
    input \/shdn ;
    input agnd;
    input in;
    inout lx;
    output out;
    input pgnd;


    initial
        begin
        end

endmodule
