-- generated by newgenasym Mon Dec 14 23:12:55 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max1921 is
    port (    
	\/shdn\:   IN     STD_LOGIC;    
	AGND:      IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	LX:        INOUT  STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	PGND:      IN     STD_LOGIC);
end max1921;
